### PR TITLE
Update description

### PR DESCRIPTION
**Pull request by justineechen**
Updated description to align with Containerize guide (that will be published).

### CODE REVIEW

**Comment by yeekangc** [comment]
It's more than the abstract i.e. page-description that we should update.  Should clarify in the introduction where appropriate too.

The description under the title in the content needs to be updated too.

I will rephrase "To containerize your ..." too to say something like, "First, containerize ..."

**Comment by yeekangc** [comment]
Please have folks review the changes and the draft before we merge, @justineechen @gkwan-ibm.  @lauracowen would be a good reviewer.

**Comment by yeekangc** [comment]
I made additional updates.  Please take a look, @justineechen @lauracowen.

**Comment by yeekangc** [comment]
@gkwan-ibm @justineechen, we should finalize the changes, merge this PR, and refresh in line with the publishing of the Containerize guide.

**Comment by gkwan-ibm** [comment]
@justineechen would you update the "Containerize your application" section title to "Running your application in Docker container"?

**Pull request merged**
